### ISSUE TITLE
"ERROR: Invalid vending object ID!"

### ISSUE THREAD

**Issue by jaymz478** [Larceny-/vending#10]
So, I got the include today. When I first started it I got spammed with: 
ERROR: Invalid vending object id! (Used ID: 1977 - Valid IDs: 955, 956 or 1302)
ERROR: Invalid vending object id! (Used ID: 1775 - Valid IDs: 955, 956 or 1302)
ERROR: Invalid vending object id! (Used ID: 1776 - Valid IDs: 955, 956 or 1302)
ERROR: Invalid vending object id! (Used ID: 1775 - Valid IDs: 955, 956 or 1302)
ERROR: Invalid vending object id! (Used ID: 1776 - Valid IDs: 955, 956 or 1302)
ERROR: Invalid vending object id! (Used ID: 1775 - Valid IDs: 955, 956 or 1302)
ERROR: Invalid vending object id! (Used ID: 1776 - Valid IDs: 955, 956 or 1302)
ERROR: Invalid vending object id! (Used ID: 1775 - Valid IDs: 955, 956 or 1302)
ERROR: Invalid vending object id! (Used ID: 1775 - Valid IDs: 955, 956 or 1302)
ERROR: Invalid vending object id! (Used ID: 1775 - Valid IDs: 955, 956 or 1302)
ERROR: Invalid vending object id! (Used ID: 1776 - Valid IDs: 955, 956 or 1302)
ERROR: Invalid vending object id! (Used ID: 1776 - Valid IDs: 955, 956 or 1302)
ERROR: Invalid vending object id! (Used ID: 1776 - Valid IDs: 955, 956 or 1302)
ERROR: Invalid vending object id! (Used ID: 1776 - Valid IDs: 955, 956 or 1302)
ERROR: Invalid vending object id! (Used ID: 1776 - Valid IDs: 955, 956 or 1302)
ERROR: Invalid vending object id! (Used ID: 1776 - Valid IDs: 955, 956 or 1302)
ERROR: Invalid vending object id! (Used ID: 1776 - Valid IDs: 955, 956 or 1302)
ERROR: Invalid vending object id! (Used ID: 1776 - Valid IDs: 955, 956 or 1302)
ERROR: Invalid vending object id! (Used ID: 1776 - Valid IDs: 955, 956 or 1302)
ERROR: Invalid vending object id! (Used ID: 1775 - Valid IDs: 955, 956 or 1302)
ERROR: Invalid vending object id! (Used ID: 1775 - Valid IDs: 955, 956 or 1302)
ERROR: Invalid vending object id! (Used ID: 1209 - Valid IDs: 955, 956 or 1302)
ERROR: Invalid vending object id! (Used ID: 1775 - Valid IDs: 955, 956 or 1302)
ERROR: Invalid vending object id! (Used ID: 1775 - Valid IDs: 955, 956 or 1302)
ERROR: Invalid vending object id! (Used ID: 1775 - Valid IDs: 955, 956 or 1302)
ERROR: Invalid vending object id! (Used ID: 1775 - Valid IDs: 955, 956 or 1302)
ERROR: Invalid vending object id! (Used ID: 1775 - Valid IDs: 955, 956 or 1302)
ERROR: Invalid vending object id! (Used ID: 1776 - Valid IDs: 955, 956 or 1302)
ERROR: Invalid vending object id! (Used ID: 1776 - Valid IDs: 955, 956 or 1302)
ERROR: Invalid vending object id! (Used ID: 1776 - Valid IDs: 955, 956 or 1302)
ERROR: Invalid vending object id! (Used ID: 1776 - Valid IDs: 955, 956 or 1302)
ERROR: Invalid vending object id! (Used ID: 1775 - Valid IDs: 955, 956 or 1302)
ERROR: Invalid vending object id! (Used ID: 1776 - Valid IDs: 955, 956 or 1302)
ERROR: Invalid vending object id! (Used ID: 1775 - Valid IDs: 955, 956 or 1302)
ERROR: Invalid vending object id! (Used ID: 1776 - Valid IDs: 955, 956 or 1302)
ERROR: Invalid vending object id! (Used ID: 1776 - Valid IDs: 955, 956 or 1302)
ERROR: Invalid vending object id! (Used ID: 1775 - Valid IDs: 955, 956 or 1302)
ERROR: Invalid vending object id! (Used ID: 1776 - Valid IDs: 955, 956 or 1302)
ERROR: Invalid vending object id! (Used ID: 1775 - Valid IDs: 955, 956 or 1302)
ERROR: Invalid vending object id! (Used ID: 1775 - Valid IDs: 955, 956 or 1302)
is there any possible fix?

-James

**Comment by Larceny-** [comment]
Sorry for late reply.

Currently, the supported vendings ids are MACHINE_SPRUNK, MACHINE_SNACK, MACHINE_SODA (http://i.imgur.com/F69UG65.jpg).

I thought those were the only existent in the game.

You can comment the lines 248 and 249 of the include as a temporary fix or use the ones i quoted above.

**Comment by Larceny-** [comment]
Fixed on version 2.1
